# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from zoo_imu/Sensor.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Sensor(genpy.Message):
  _md5sum = "ae4bc18611c4c4b13dc973d79b08faf4"
  _type = "zoo_imu/Sensor"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 ultra1
int16 ultra2
int16 ultra3
int16 ultra4
int8 grey_sensor
int8 collision
int16 voltage
int16 current
"""
  __slots__ = ['ultra1','ultra2','ultra3','ultra4','grey_sensor','collision','voltage','current']
  _slot_types = ['int16','int16','int16','int16','int8','int8','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ultra1,ultra2,ultra3,ultra4,grey_sensor,collision,voltage,current

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Sensor, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ultra1 is None:
        self.ultra1 = 0
      if self.ultra2 is None:
        self.ultra2 = 0
      if self.ultra3 is None:
        self.ultra3 = 0
      if self.ultra4 is None:
        self.ultra4 = 0
      if self.grey_sensor is None:
        self.grey_sensor = 0
      if self.collision is None:
        self.collision = 0
      if self.voltage is None:
        self.voltage = 0
      if self.current is None:
        self.current = 0
    else:
      self.ultra1 = 0
      self.ultra2 = 0
      self.ultra3 = 0
      self.ultra4 = 0
      self.grey_sensor = 0
      self.collision = 0
      self.voltage = 0
      self.current = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4h2b2h().pack(_x.ultra1, _x.ultra2, _x.ultra3, _x.ultra4, _x.grey_sensor, _x.collision, _x.voltage, _x.current))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.ultra1, _x.ultra2, _x.ultra3, _x.ultra4, _x.grey_sensor, _x.collision, _x.voltage, _x.current,) = _get_struct_4h2b2h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4h2b2h().pack(_x.ultra1, _x.ultra2, _x.ultra3, _x.ultra4, _x.grey_sensor, _x.collision, _x.voltage, _x.current))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.ultra1, _x.ultra2, _x.ultra3, _x.ultra4, _x.grey_sensor, _x.collision, _x.voltage, _x.current,) = _get_struct_4h2b2h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4h2b2h = None
def _get_struct_4h2b2h():
    global _struct_4h2b2h
    if _struct_4h2b2h is None:
        _struct_4h2b2h = struct.Struct("<4h2b2h")
    return _struct_4h2b2h
